### ISSUE TITLE
zsh: exec format error: ./copilot2gpt

### ISSUE THREAD

**Issue by Maydaytyh** [ljnchn/cocopilot2gpt#1]
m芯片好像不支持？
<img width="497" alt="image" src="https://github.com/ljnchn/cocopilot2gpt/assets/13815598/a1965c07-05bf-498b-94ae-5d7f54e58df0">

**Comment by ljnchn** [comment]
手头没有m芯片的机器，你试试 arm 的release
https://github.com/ljnchn/cocopilot2gpt/releases/download/v0.2/copilot2gpt-linux-arm64-v0.2.tar.gz
