### ISSUE TITLE
请求限制

### ISSUE THREAD

**Issue by mamingsuper** [ljnchn/cocopilot2gpt#10]
感谢大佬开发，有个问题想请教，我部署后，
调用api做文本分析，发现请求300次后就出现了429代码，
发现是api key, ghu_ 过期了，拿了新的之后就继续可以工作。
想请问这一步可以自动化吗？科研自用，感谢！

**Comment by ljnchn** [comment]
请求太频繁是会429的，总是频繁请求还有可能封号的，要限制一下。
自动获取ghu目前实现不了。
