### ISSUE TITLE
docker部署之后好像缺文件

### ISSUE THREAD

**Issue by docker-master** [ljnchn/cocopilot2gpt#12]
我不太会用，软路由docker部署的，docker部署一会就停止了，是不是要下载文件

**Comment by AlanWang2333** [comment]
> 我不太会用，软路由docker部署的，docker部署一会就停止了，是不是要下载文件，我看到文件是windows的和linux的

**Comment by ljnchn** [comment]
是不是端口冲突了？看看日志有没有提示

**Comment by docker-alex-ai** [comment]
> 是不是端口冲突了？看看日志有没有提示

version: "3.3"
services:
  copilot2gpt:
    container_name: AI-copilot2gpt_Dockge
    image: ersichub/copilot2gpt
    restart: unless-stopped
    ports:
      - 8081:8081
    networks:
      - chatgpt
networks:
  chatgpt:
    external: true
这是我的compose.ymal
![image](https://github.com/ljnchn/cocopilot2gpt/assets/58912611/cdd71315-d646-49ec-891a-648685bd6007)
AI-copilot2gpt_Dockge  | exec ./copilot2gpt: exec format error
我问了一下GPT,他说可能是操作系统版本不兼容，我的设备是iStoreOS X64架构的软路由

**Comment by docker-alex-ai** [comment]
我compose目录里面放了copilot2gpt-linux-64-v0.6.1.tar的解压文件，我是x86架构的，可惜还是 exec ./copilot2gpt: exec format error
