### ISSUE TITLE
降级为gpt-3了，不知道是太多次了，还是官方降了

### ISSUE THREAD

**Issue by whoisfucker** [ljnchn/cocopilot2gpt#5]
![image](https://github.com/ljnchn/cocopilot2gpt/assets/4996887/c7dee3a5-4410-4a54-9635-dfb3a18801c5)

**Comment by whoisfucker** [comment]
我的用了测试了以下基本是3.5的结果，以前都很智能，今天降智了。
测试问题 1：昨天的当天是明天的什么？
GPT-3.5 回复：昨天
GPT-4 回复：前天

 测试问题 2：树上 9 只鸟，打掉 1 只，还剩几只？
GPT-3.5 回复：8 只
GPT-4 回复：0 只，其他被吓跑了

测试问题 3：鲁迅为什么暴打周树人
GPT-3.5 回复：稀奇古怪的乱编理由
GPT-4 回复：鲁迅和周树人是同一个人

**Comment by ljnchn** [comment]
我刚试了是正常的，你选的是gpt-4吗，选1106后缀什么的，会重定向到3.5

**Comment by whoisfucker** [comment]
了解了，应该是这个原因，现在测试可以用了
