### ISSUE TITLE
可以组轮询吗？

### ISSUE THREAD

**Issue by sdgsgsdf** [ljnchn/cocopilot2gpt#8]
大佬这个可以多放几个ghu，然后轮询使用吗？

**Comment by ljnchn** [comment]
目前没做多guh轮询，可以放到one-api里面搞，一个ghu对应一个渠道

**Comment by sdgsgsdf** [comment]
> 目前没做多guh轮询，可以放到one-api里面搞，一个ghu对应一个渠道

soga，一个ghu设置一个渠道就行了嘛？不可以直接在一个地址里填写多个ghu吗？

**Comment by ljnchn** [comment]
对，一个ghu对应一个渠道，这样轮询，失效自动禁用啥的都可以了

**Comment by sdgsgsdf** [comment]
> 对，一个ghu对应一个渠道，这样轮询，失效自动禁用啥的都可以了

对了大佬，我看他渠道哪里，有批量创建选项，可以填入多个key。这个选项不是轮询吗？这个里面填入多个key和一ghu创建一个渠道，两者是有区别的吗？
